People json
Code-4-Community/c4cneu.com pull request #36
Opened 2020-08-25 18:30 UTC by kiminlee2000225

2020-08-26 00:04 UTC, jackblanc requested changes
Let me know if you have any questions on the Typescript stuff 👍

2020-08-26 00:04 UTC, jackblanc commented on src/components/PeopleData.tsx
> +const people = [
We want to have this as a typed object:
```
interface Person {
  readonly name: string;
  readonly position: string;
  ....
}
```

Then have: 
`const people: People[] = [...`

2020-08-26 00:04 UTC, jackblanc commented on src/components/People.tsx
> +              {PeopleData.map(person => <Member name={person.name} position={person.position} image={person.image} linkedin={person.linkedin} email={person.email} />)}
The `Member` component should take as props a `Person`.
You can do `<Member person={person} />` (might have to give them different names)

2020-08-31 17:27 UTC, rymaju commented
See #40

2020-08-31 17:27 UTC, closed without merging